import Head from "next/head";
import Hero from "@/components/hero";
import Footer from "@/components/footer";
import React from "react";
import PropertyHero from "@/components/property_hero";
import useFetch from "@/hooks/useFetch";

export default function Properties() {
    const {data, loading, error} = useFetch(`http://localhost:8001/api/properties`);

    if (loading) return <div>Loading...</div>;
    if (error) return <div>Error: {error.message}</div>;
    if (!data) return null;

    return (
        <>
            <Head>
                <title>Real Estate </title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="dark:bg-bgDark">
                <PropertyHero
                    address="225 S 1st St Brooklyn, NY 11211"
                    phone="(929) 123-4567"
                    email="constrctr@restate.com"
                />
                <Footer/>
            </div>
        </>
    )
}